<a href="https://colab.research.google.com/github/Ayodeji-python/Modern_Data_Science/blob/master/code_02_XX_Incident_Root_Cause_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Incident Root Cause Analysis 

Incident Reports in ITOps usually states the symptoms. Identifying the root cause of the symptom quickly is a key determinant to reducing resolution times and improving user satisfaction.

In [ ]:
#Install all related packages. If you find additional packages missing, please follow the same technique.
#If you are not using anaconda, then use pip to install the same packages

import sys
!conda install --yes --prefix {sys.prefix} pandas tensorflow scikit-learn

Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.2
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /opt/anaconda3/envs/itops

  added / updated specs:
    - pandas
    - scikit-learn
    - tensorflow


The following NEW packages will be INSTALLED:

  _tflow_select      pkgs/main/osx-64::_tflow_select-2.3.0-mkl
  absl-py            pkgs/main/osx-64::absl-py-0.9.0-py37_0
  astor              pkgs/main/osx-64::astor-0.8.0-py37_0
  blas               pkgs/main/osx-64::blas-1.0-mkl
  c-ares             pkgs/main/osx-64::c-ares-1.15.0-h1de35cc_1001
  gast               pkgs/main/osx-64::gast-0.2.2-py37_0
  google-pasta       pkgs/main/noarch::google-pa

# 02.04. Preprocessing Incident Data

### Loading the Dataset

In [2]:
import pandas as pd
import os
import tensorflow as tf

#Load the data file into a Pandas Dataframe
symptom_data = pd.read_csv("root_cause_analysis.csv")

#Explore the data loaded
print(symptom_data.dtypes)
symptom_data.head()

ID              int64
CPU_LOAD        int64
MEMORY_LOAD     int64
DELAY           int64
ERROR_1000      int64
ERROR_1001      int64
ERROR_1002      int64
ERROR_1003      int64
ROOT_CAUSE     object
dtype: object


ID  CPU_LOAD  MEMORY_LOAD  ...  ERROR_1002  ERROR_1003     ROOT_CAUSE
0   1         0            0  ...           0           1         MEMORY
1   2         0            0  ...           0           1         MEMORY
2   3         0            1  ...           1           1         MEMORY
3   4         0            1  ...           0           1         MEMORY
4   5         1            1  ...           1           0  NETWORK_DELAY

[5 rows x 9 columns]

### Convert  data

Input data needs to be converted to formats that can be consumed by ML algorithms

In [10]:
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()
symptom_data['ROOT_CAUSE'] = label_encoder.fit_transform(
                                symptom_data['ROOT_CAUSE'])

symptom_data['ROOT_CAUSE']

0      1
1      1
2      1
3      1
4      2
      ..
995    0
996    2
997    1
998    2
999    0
Name: ROOT_CAUSE, Length: 1000, dtype: int64

In [4]:
#Convert Pandas DataFrame to a numpy vector
np_symptom = symptom_data.to_numpy().astype(float)

np_symptom

array([[   1.,    0.,    0., ...,    0.,    1.,    1.],
       [   2.,    0.,    0., ...,    0.,    1.,    1.],
       [   3.,    0.,    1., ...,    1.,    1.,    1.],
       ...,
       [ 998.,    1.,    1., ...,    0.,    0.,    1.],
       [ 999.,    0.,    1., ...,    0.,    0.,    2.],
       [1000.,    1.,    0., ...,    1.,    0.,    0.]])

In [5]:
#Extract the feature variables (X)
X_train = np_symptom[:,1:8]

X_train

array([[0., 0., 0., ..., 1., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 1., ..., 0., 1., 1.],
       ...,
       [1., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 1., 1., 0.]])

In [9]:
#Extract the target variable (Y), convert to one-hot-encoding
Y_train=np_symptom[:,8]
Y_train = tf.keras.utils.to_categorical(Y_train,3)
Y_train


array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [11]:
print("Shape of feature variables :", X_train.shape)
print("Shape of target variable :",Y_train.shape)

Shape of feature variables : (1000, 7)
Shape of target variable : (1000, 3)


## 02.05. Building the Model with Keras

In [14]:
len(label_encoder.classes_)

3

In [12]:
from tensorflow import keras
from tensorflow.keras import optimizers
from tensorflow.keras.regularizers import l2

#Setup Training Parameters
EPOCHS=20
BATCH_SIZE=100
VERBOSE=1
OUTPUT_CLASSES=len(label_encoder.classes_)
N_HIDDEN=128
VALIDATION_SPLIT=0.2

#Create a Keras sequential model
model = tf.keras.models.Sequential()
#Add a Dense Layer
model.add(keras.layers.Dense(N_HIDDEN,
                             input_shape=(7,),
                              name='Dense-Layer-1',
                              activation='relu'))

#Add a second dense layer
model.add(keras.layers.Dense(N_HIDDEN,
                              name='Dense-Layer-2',
                              activation='relu'))

#Add a softmax layer for categorial prediction
model.add(keras.layers.Dense(OUTPUT_CLASSES,
                             name='Final',
                             activation='softmax'))

#Compile the model, using Adam optimizer
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

#Build the model
model.fit(X_train,
          Y_train,
          batch_size=BATCH_SIZE,
          epochs=EPOCHS,
          verbose=VERBOSE,
          validation_split=VALIDATION_SPLIT)

model.summary()

Epoch 1/20
8/8 [==============================] - 1s 26ms/step - loss: 1.0844 - accuracy: 0.4638 - val_loss: 0.9814 - val_accuracy: 0.7900
Epoch 2/20
8/8 [==============================] - 0s 4ms/step - loss: 0.9099 - accuracy: 0.7900 - val_loss: 0.8590 - val_accuracy: 0.7800
Epoch 3/20
8/8 [==============================] - 0s 4ms/step - loss: 0.7577 - accuracy: 0.7875 - val_loss: 0.7300 - val_accuracy: 0.7800
Epoch 4/20
8/8 [==============================] - 0s 4ms/step - loss: 0.6249 - accuracy: 0.8050 - val_loss: 0.6275 - val_accuracy: 0.7900
Epoch 5/20
8/8 [==============================] - 0s 4ms/step - loss: 0.5308 - accuracy: 0.8112 - val_loss: 0.5674 - val_accuracy: 0.7800
Epoch 6/20
8/8 [==============================] - 0s 4ms/step - loss: 0.4751 - accuracy: 0.8213 - val_loss: 0.5458 - val_accuracy: 0.8000
Epoch 7/20
8/8 [==============================] - 0s 4ms/step - loss: 0.4456 - accuracy: 0.8338 - val_loss: 0.5308 - val_accuracy: 0.8100
Epoch 8/20
8/8 [=================

## 02.06. Predicting Root Causes

In [ ]:
#Pass individual flags to Predict the root cause
CPU_LOAD=1
MEMORY_LOAD=0
DELAY=0
ERROR_1000=0
ERROR_1001=1
ERROR_1002=1
ERROR_1003=0

prediction=model.predict_classes(
    [[CPU_LOAD,MEMORY_LOAD,DELAY,
      ERROR_1000,ERROR_1001,ERROR_1002,ERROR_1003]])

print(label_encoder.inverse_transform(prediction))

['DATABASE_ISSUE']


In [ ]:
#Predicting as a Batch
print(label_encoder.inverse_transform(
        model.predict_classes([[1,0,0,0,1,1,0],
                                [0,1,1,1,0,0,0],
                                [1,1,0,1,1,0,1],
                                [0,0,0,0,0,1,0],
                                [1,0,1,0,1,1,1]])))

['DATABASE_ISSUE' 'NETWORK_DELAY' 'MEMORY' 'DATABASE_ISSUE'
 'DATABASE_ISSUE']
